#pragma once 

#define UNVALID_DATE "\n\033[3;31merror: unvalid date format\nusage: yyyy-mm-dd\n"
#define UNVALID_DATE_RANGE "\n\033[3;31merror: unvalid date format\nusage: yyyy-mm-dd (valid range: 2009-01-03 to 2023-31-12)\n"
#define UNVALID_DATE_DAY "\n\033[3;31merror: unvalid date\n"
#define UNVALID_E_RATE "\n\033[3;31merror: unvalid e_rate format\n"
#define UNVALID_INPUT "\n\033[3;31merror : unvalid input\nusage : ./btc <file> \"value\"\n"
#define UNVAILD_CSV_HEADER "\n\033[3;31merror: unvalid csv header\n"
#define UNABLE_TO_OPEN "\n\033[3;31merror: failed to open file\n"
#define EMPTY_CSV_FILE "\n\033[3;31merror: empty csvfile\n"
#define NO_DATA "\n\033[3;31merror: data required in csv file\n"
#define EMPTY_INPUT_FILE "\n\033[3;31merror: empty inputfile\n"
#define UNVAILD_INPUT_HEADER "\n\033[3;31merror: unvalid input header\n"
#define UNVALID_VALUE "\n\033[3;31merror: unvalid value\n"
#define NUMBER_TOO_LARGE "\n\033[3;31mError: too large a number.\n"
#define NEGATIVE_NUM "\n\033[3;31mError: not a positve number.\n"
#define UNVAILD_INPUT_FORMAT "\n\033[3;31mError: unvalid input format\n"